import Link from "next/link";
import { instructions } from "@/lib/instructions";
export default function Information() {
  return <main className="max-w-3xl mx-auto p-6 sm:p-10 space-y-8">
    <Link href="/" className="underline">Zpět na úvod</Link>
    <h1 className="text-3xl font-bold">Informace o telemedicínské konzultaci</h1>
    <div className="bg-warning-50 border rounded-lg p-4"><strong>Zkušební provoz.</strong> Používejte smyšlené údaje a testovací přílohy. Před používáním se skutečnými pacienty musí provozovatel doplnit své údaje, informace o zpracování dat a doložit smluvní, bezpečnostní a provozní podmínky.</div>
    <section className="space-y-3"><h2 className="text-xl font-semibold">Jak konzultace probíhá</h2><ol className="list-decimal pl-5 space-y-2"><li>Ordinace s vámi domluví termín a způsob ověření totožnosti a předá vám osobní pozvánku.</li><li>Ve stejném prohlížeči vyplníte údaje, projdete poučení a vstoupíte do čekárny.</li><li>Lékař vás pozve do videohovoru; ověříte totožnost obou stran.</li><li>Po konzultaci lékař doplní závěr a doporučení a přenese zápis a potřebné přílohy do své zdravotnické dokumentace.</li></ol></section>
    <section className="space-y-3"><h2 className="text-xl font-semibold">Vhodnost a omezení péče na dálku</h2><p>{instructions.service}</p><p>{instructions.urgent}</p><p>{instructions.consent}</p></section>
    <section className="space-y-3"><h2 className="text-xl font-semibold">Ověření totožnosti a soukromí</h2><p>{instructions.identity}</p><p>{instructions.privacy}</p></section>
    <section className="space-y-3"><h2 className="text-xl font-semibold">Videohovor a záznam</h2><p>Videohovor probíhá ve vložené místnosti Whereby. Aplikace vytváří malé zamčené místnosti; jejich dokumentace popisuje koncové šifrování zvuku a obrazu. Provozovatel musí ověřit nastavení služby pro svůj účet.</p><p>{instructions.recording}</p></section>
    <section className="space-y-3"><h2 className="text-xl font-semibold">Dokumenty, poznámky a výsledný zápis</h2><p>{instructions.attachments}</p><p>Oprávněný personál ordinace vidí poznámky a přílohy dané ordinace. Dokončené podklady a jejich opravy mají oddělené uložené verze. Konečnou zdravotnickou dokumentaci vede a autorizuje poskytovatel ve svém dokumentačním systému.</p><p>Trvání v zápisu označuje interval od zahájení do ukončení konzultace v aplikaci; nejde o měření skutečného spojení kamery ani o automatický podklad pro vykázání pojišťovně.</p></section>
    <section className="space-y-3"><h2 className="text-xl font-semibold">Výpadek a kontakt</h2><p>{instructions.outage}</p><p>Údaje konkrétní ordinace a domluveného lékaře se zobrazují u vaší pozvánky. Pro akutní pomoc použijte tísňovou linku.</p></section>
    <section className="space-y-3"><h2 className="text-xl font-semibold">Ochrana osobních údajů</h2><p>Aplikace pracuje s identifikačními a kontaktními údaji, termínem, důvodem konzultace, poznámkami, přílohami a evidencí přístupů. Zpracování zajišťují také služby Supabase, Netlify a Whereby v rozsahu své funkce.</p><p>Identitu správce, právní důvody zpracování, příjemce, předávání do zahraničí, doby uchování a kontakty pro uplatnění práv musí stanovit konkrétní provozovatel. Jeho informace jsou dostupné u pozvánky, jakmile je ordinace doplní. Tento obecný popis nenahrazuje úplnou informační povinnost provozovatele.</p><p>Nezbytné přístupové cookies drží přihlášení a pacientskou relaci. Aplikace sama nenasazuje reklamní ani analytické měření; vložená služba Whereby má vlastní podmínky zpracování.</p><p>Práva mohou zahrnovat přístup k údajům, opravu a další práva podle podmínek GDPR; výmaz dokumentace může být omezen zákonnou povinností jejího uchování. Stížnost lze podat Úřadu pro ochranu osobních údajů.</p></section>
    <section className="space-y-3"><h2 className="text-xl font-semibold">Podklady pro provozovatele</h2><p>Tato aplikace sama nepotvrzuje právní soulad celé služby. Je nutné ověřit aktuální požadavky na telemedicínu, zdravotnickou dokumentaci, ochranu údajů a případně kybernetickou bezpečnost.</p><ul className="list-disc pl-5"><li><a className="underline" href="https://e-sbirka.gov.cz/sb/2011/372">Zákon č. 372/2011 Sb.</a></li><li><a className="underline" href="https://e-sbirka.gov.cz/sb/2025/30">Vyhláška č. 30/2025 Sb.</a></li><li><a className="underline" href="https://e-sbirka.gov.cz/sb/2024/444">Vyhláška č. 444/2024 Sb.</a></li><li><a className="underline" href="https://ncez.mzcr.cz/cs/standardy-elektronickeho-zdravotnictvi/technicky-standard-telemedicinskych-zdravotnich-sluzeb-dle">Technický standard a odkaz na jeho aktualizace</a></li></ul></section>
  </main>;
}
